---
- hosts: all
  become : yes
  tasks:
  - name: i want install tree
    apt:
     name: tree
     state: present

  - name : i want to install git
    apt:
     name: git
     state: present

  - name : i want to install apache2
    apt:
     name: apache2
     state: present

  - name : i want to start apache2
    service:
     name: apache2
     state: started

